apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
spec:
  selector:
    matchLabels:
      app: task
  replicas: 1
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
        - name: task
          image: keithfajardo/kubernetes-task-app:3
          env:
            - name: TASKS_FOLDER
              value: tasks
            - name: AUTH_ADDRESS
              value: "auth-service.default"