apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: users
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: keithfajardo/kubernetes-users-app:3
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default" # Here, we are using the service name and with ".default".
                                            # the ".default" notation is the namespace wherein the default namespace is "default".
                                            # This is accessible by running kubectl get namespaces
                                            # This is very similar to docker-compose syntax wherein we use the name of the service to get the hostname of the a container.
