apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: users
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: keithfajardo/kubernetes-users-app:3
          # We don't need the env because we are using Kubernetes Environment variables
          # since we have service named auth-service, Kubernetes will automatically create a env variable called AUTH_SERVICE
          # then we append a suffix of SERVICE_HOST to dynamically get the IP address of the service
          # env:
          #   - name: AUTH_ADDRESS
          #     value: 10.99.69.155 # We can get the IP of the auth-service by runnign kubectl get services.