apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: users
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: keithfajardo/kubernetes-users-app:2
          env:
            - name: AUTH_ADDRESS
              value: localhost
        - name: auth
          image: keithfajardo/kubernetes-auth-app:1